# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  # <combine>
  # <age_days>
  # <count_days>
  # <sorted_bars>
  # <change_lagged>
  # <rate_of_return>
  ":=",
  # <combine>
  "combined",
  # <rate_of_return>
  "copy",
  # <forager_data>
  "date_of_acceptance",
  # <forager_data>
  "date_of_release",
  # <forager_data>
  "date_of_service",
  # <forager_data>
  "date_of_submission",
  # <forager_data>
  "dates",
  # <id_runs>
  "group",
  # <id_runs>
  "group_size",
  # <make_interval>
  "interval",
  # <id_runs>
  "key",
  # <rate_of_return>
  "lg",
  # <count_prop>
  # <count_prop_multi>
  # <count_wide>
  # <describe>
  "n",
  # <describe>
  "type",
  # <describe>
  # <id_runs>
  "value",
  # <describe>
  "variable",
  NULL
))
