# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  # <change_lagged>
  # <rate_of_return>
  # <age_days>
  # <count_days>
  ":=",
  # <rate_of_return>
  "copy",
  # <forager_data>
  "date_of_acceptance",
  # <forager_data>
  "date_of_release",
  # <forager_data>
  "date_of_service",
  # <forager_data>
  "date_of_submission",
  # <make_interval>
  "interval",
  # <rate_of_return>
  "lg",
  # <count_prop>
  # <count_prop_multi>
  # <count_wide>
  "n",
  NULL
))
